name: myWorkflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install reprositore and dependencies
        uses: actions/checkout@v4      
      - run: make install-deps
      - name: Run test and eslint
        uses: actions/checkout@v4   
      - run: make lint
      - run: make test